export const ACTION_TYPES = {
  GET_DATA: 'GET_DATA',
  ADD_CART: 'ADD_CART',
  REMOVE_CART: 'REMOVE_CART',
  INCREMENT_PIZZA: 'INCREMENT_PIZZA',
  DECREMENT_PIZZA: 'DECREMENT_PIZZA',
  CONFIRM_ORDER: 'CONFIRM_ORDER',
  SET_USER: 'SET_USER',
  CLEAR_CART: 'CLEAR_CART',
};
